version: "3.10"

services:
  db:
    container_name: journeed-db
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8

  web:
    container_name: Journeed
    build: .
    restart: "always"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./static/:/code/static/
      - ./media/:/code/media/
    links:
      - db
    env_file: .env
    depends_on:
      - db

networks:
  default:
    external:
      name: nginx-proxy