# Generated by Django 5.0.4 on 2024-06-20 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partnership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotels',
            name='partnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnership.partnership'),
        ),
        migrations.AddField(
            model_name='guide',
            name='partnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnership.partnership'),
        ),
        migrations.AddField(
            model_name='flight',
            name='partnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnership.partnership'),
        ),
        migrations.AddField(
            model_name='rentcar',
            name='partnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnership.partnership'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='partnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnership.partnership'),
        ),
    ]
