# Generated by Django 5.0.4 on 2024-05-20 08:40

import django.db.models.deletion
import services.uploader
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='role',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='name',
        ),
        migrations.AddField(
            model_name='partnership',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='partner_photo',
            field=models.ImageField(upload_to=services.uploader.Uploader.partnership_photo_uploader),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnership.partnership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnership.partnership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnership.partnership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnership.partnership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnership.partnership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
