# Generated by Django 5.0.4 on 2024-06-10 12:24

import services.uploader
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_advices_advice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=services.uploader.Uploader.gallery_image_uploader)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='advice',
            options={'ordering': ('-created_at',), 'verbose_name': 'Advice', 'verbose_name_plural': 'Advices'},
        ),
    ]
