# Generated by Django 5.0.4 on 2024-06-10 12:47

import services.uploader
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_pastime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastime',
            name='image',
            field=models.ImageField(upload_to=services.uploader.Uploader.pastime_photo_uploader),
        ),
    ]
