# Generated by Django 5.0.4 on 2024-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
