# Generated by Django 5.0.4 on 2024-07-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carreview_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carreview',
            options={'ordering': ('-created_at',), 'verbose_name': 'review', 'verbose_name_plural': 'Car reviews'},
        ),
    ]
