# Generated by Django 5.0.4 on 2024-04-28 07:00

import services.uploader
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head', models.CharField(max_length=200)),
                ('first_content', models.TextField(blank=True, null=True)),
                ('second_content', models.TextField(blank=True, null=True)),
                ('home_background', models.ImageField(upload_to=services.uploader.Uploader.head_background_uploader)),
                ('home_banner', models.ImageField(upload_to=services.uploader.Uploader.head_background_uploader)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
