# Generated by Django 5.0.4 on 2024-06-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialoffer',
            options={'ordering': ('-created_at',), 'verbose_name': 'Special Offer', 'verbose_name_plural': 'Special Offers'},
        ),
    ]
