# Generated by Django 5.0.4 on 2024-07-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialOffer',
        ),
    ]
