# Generated by Django 5.0.4 on 2024-06-19 07:37

import services.uploader
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_specialoffer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(upload_to=services.uploader.Uploader.special_offer_image_uploader),
        ),
    ]
