# Generated by Django 5.0.4 on 2024-05-21 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.story'),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storycommentlike',
            name='story_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.storycomment'),
        ),
        migrations.AddField(
            model_name='storycommentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storylike',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.story'),
        ),
        migrations.AddField(
            model_name='storylike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
