# Generated by Django 5.0.4 on 2024-05-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_storycommentliked_storyliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storycommentliked',
            name='like',
        ),
    ]
