# Generated by Django 5.0.4 on 2024-05-12 08:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_remove_storycommentliked_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoryCommentLiked',
            new_name='StoryCommentLike',
        ),
        migrations.RenameModel(
            old_name='StoryLiked',
            new_name='StoryLike',
        ),
    ]
